
# This file is automatically generated, you probably don't want to edit this

supercodeOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "supercodeOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            varOptions = NULL, ...) {

            super$initialize(
                package="SuperCode",
                name="supercode",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..varOptions <- jmvcore::OptionArray$new(
                "varOptions",
                varOptions,
                items="(vars)",
                template=jmvcore::OptionGroup$new(
                    "varOptions",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL,
                            content="$key"),
                        jmvcore::OptionList$new(
                            "coding",
                            NULL,
                            options=list(
                                "dummy",
                                "simple",
                                "deviation",
                                "poly",
                                "helmert",
                                "revhelmert",
                                "forward",
                                "backward"),
                            default="dummy"),
                        jmvcore::OptionLevel$new(
                            "ref",
                            NULL),
                        jmvcore::OptionBool$new(
                            "standardize",
                            NULL,
                            default=FALSE),
                        jmvcore::OptionBool$new(
                            "integerize",
                            NULL,
                            default=FALSE))))
            private$..outputCols <- jmvcore::OptionOutput$new(
                "outputCols")

            self$.addOption(private$..vars)
            self$.addOption(private$..varOptions)
            self$.addOption(private$..outputCols)
        }),
    active = list(
        vars = function() private$..vars$value,
        varOptions = function() private$..varOptions$value,
        outputCols = function() private$..outputCols$value),
    private = list(
        ..vars = NA,
        ..varOptions = NA,
        ..outputCols = NA)
)

supercodeResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "supercodeResults",
    inherit = jmvcore::Group,
    active = list(
        preview = function() private$.items[["preview"]],
        outputCols = function() private$.items[["outputCols"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Super Code")
            self$add(jmvcore::Array$new(
                options=options,
                name="preview",
                title="Contrast Matrix Preview",
                items="(vars)",
                template=jmvcore::Table$new(
                    options=options,
                    title="$key",
                    columns=list())))
            self$add(jmvcore::Output$new(
                options=options,
                name="outputCols",
                title="Coded Columns",
                initInRun=TRUE))}))

supercodeBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "supercodeBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "SuperCode",
                name = "supercode",
                version = c(0,0,1),
                options = options,
                results = supercodeResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Super Code
#'
#' 
#' @param data .
#' @param vars .
#' @param varOptions .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$preview} \tab \tab \tab \tab \tab an array of tables \cr
#'   \code{results$outputCols} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' @export
supercode <- function(
    data,
    vars,
    varOptions) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("supercode requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))

    for (v in vars) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- supercodeOptions$new(
        vars = vars,
        varOptions = varOptions)

    analysis <- supercodeClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

